name: Upptime
on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  upptime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Upptime
        run: |
          npx @upptime/uptime-monitor@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
